# Generated by Django 3.2.7 on 2022-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDrawnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], max_length=1, null=True)),
                ('status', models.CharField(choices=[(0, 'Moderation'), (1, 'Confirmed')], default=0, max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
